Traceback (most recent call last):
  File "/home/mis/Bureau/Scheduling Problem/rc2Solver.py", line 11, in <module>
    wcnf = WCNF(from_file=instance_file)
  File "/home/mis/Bureau/Scheduling Problem/venv/lib/python3.10/site-packages/pysat/formula.py", line 3631, in __init__
    self.from_file(from_file, comment_lead, compressed_with='use_ext')
  File "/home/mis/Bureau/Scheduling Problem/venv/lib/python3.10/site-packages/pysat/formula.py", line 3678, in from_file
    with FileObject(fname, mode='r', compression=compressed_with) as fobj:
  File "/home/mis/Bureau/Scheduling Problem/venv/lib/python3.10/site-packages/pysat/_fileio.py", line 108, in __init__
    self.open(name, mode=mode, compression=compression)
  File "/home/mis/Bureau/Scheduling Problem/venv/lib/python3.10/site-packages/pysat/_fileio.py", line 123, in open
    self.fp = open(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'instance/2021/4_session_file.wcnf'

real	0m0,428s
user	0m0,601s
sys	0m0,881s
